### ISSUE TITLE
the c code cannot compile on windows, due to doublemetaphone/double_metaphone.cc wrong encoding 

### ISSUE THREAD

**Issue by LeiYangGH** [dedupeio/doublemetaphone#8]
Steps:
1. Create python 3.8.3 32bit virtual env.
2. Clone the repo.
3. pip3.8.exe --no-cache-dir install  path to doublemetaphone. open doublemetaphone/double_metaphone.cc by notepad and can see the encoding is ansi.
4. several errors, such as line  634 `case 'Ñ'`
5. save the file as utf-8 encoding. then pip install again.
6. now succeed.

**Comment by fgregg** [comment]
can't reproduce
